---
kind: pipeline
type: docker
name: default

volumes:
  - name: cache
    host:
      path: /tmp/cache/ansible-role-borgbackup

workspace:
  path: ${DRONE_REPO_NAME}

steps:
  - name: restore-cache-with-filesystem
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "requirements.txt" }}'
      archive_format: "gzip"
      mount:
        - '.virtualenv'
    volumes:
      - name: cache
        path: /tmp/cache

  - name: install-dependencies
    depends_on: [restore-cache-with-filesystem]
    image: python:3.8
    commands:
      # If the virtualenv dir is not cached create it
      - '[ ! -d ".virtualenv" ] && python -m venv .virtualenv'
      - . .virtualenv/bin/activate
      - pip install -r requirements.txt

  - name: test
    depends_on: [install-dependencies]
    image: python:3.8
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: eu-west-1
      USER: root
      ANSIBLE_FORCE_COLOR: '1'
    volumes:
      - name: cache
        path: '/usr/local/lib/python3.9/site-packages'
    commands:
      - . .virtualenv/bin/activate
      - molecule test
      - black --check .
      - isort --check-only .

  - name: rebuild-cache-with-filesystem
    depends_on: [install-dependencies]
    image: meltwater/drone-cache:dev
    pull: true
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "requirements.txt" }}'
      archive_format: "gzip"
      mount:
        - '.virtualenv'
    volumes:
    - name: cache
      path: /tmp/cache

  - name: fail-on-debug-instruction
    image: alpine
    commands:
      - grep '|| sleep' .drone.yml || exit 1
