---
- name: Install fetch
  become: true
  tags: fetch
  get_url:
    url: https://github.com/gruntwork-io/fetch/releases/download/v0.4.1/fetch_linux_amd64
    dest: /usr/local/bin/fetch
    mode: 0755
    force: true
