---
- include_tasks: ./install_fetch.yml

- name: Install borg
  shell: >-
    fetch --repo
    https://github.com/borgbackup/borg
    --release-asset="borg-linux64"
    --tag={{ borg_version }}
    /tmp

- name: Move borg binary
  become: true
  copy:
    src: /tmp/borg-linux64
    dest: /usr/local/bin/borg
    remote_src: true
    mode: 0755
