---
- name: Assert mandatory vars
  when: borgmatic_create_config_file
  assert:
    that:
      - borg_password is defined
      - borg_ssh_key is defined

- no_log: '{{ no_log | default(true) }}'
  set_fact:
    borgmatic_cfg: >-
      {{ borgmatic_config_defaults | combine(borgmatic_config, recursive=borgmatic_config_merge_recursive)}}

- include_tasks: ./install_borg.yml

- include_tasks: ./install_borgmatic.yml

- include_tasks: ./create_files.yml

- name: Initiate the repo
  shell: 'borgmatic init --encryption repokey -c {{ borgmatic_config_file }}'
  retries: 2
  delay: 1
  register: _result
  until: _result is success
